repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: # arguments to configure black
            - --line-length=120
            - --include='\.pyi?$'
