version: 1
formatters:
  simple:
    format: '%(asctime)s loglevel=%(levelname)-6s logger=%(name)s %(funcName)s() L%(lineno)-4d %(message)s'
  detailed:
    format: '%(asctime)s loglevel=%(levelname)-6s logger=%(name)s %(funcName)s() L%(lineno)-4d %(message)s   call_trace=%(pathname)s L%(lineno)-4d'
handlers:
  console:
    class: logging.StreamHandler
    formatter: detailed
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]
loggers:
  train:
    level: DEBUG
    handlers: [console]
    propagate: no
